@startuml Move
participant Szoba as sz
participant Karakter as k
participant Ajto as a

k->sz : Move

loop door_num
    sz->a ++: askDirections
    return ret(directions)
end

alt Szoba.capacity!=full && there is entrance
    sz-->k : MoveAccept
    sz->>sz : setParticipants
    k->>k : setRoom
    sz->sz : getGased

    alt gased = true
        sz->k ++: protection(bool)
        return bool
        alt karakter has no protection
            sz->>k : paralyze
        end
    else
    end
    
else
    sz-->k : MoveDeny
end

@enduml