@startuml camembert

title activate Camembert

participant Student as s
participant Camembert as c
participant Room as r

s -> c ++: activate()

c -> s ++: getLocation()
s--> c --: Room

c->r : setGassed()

r-->c

c-->s --:


@enduml