@startuml drop

Title hallgatói tárgyeldobás

actor "u: User" as u
participant "c : Character" as char
participant "i : Item" as t
participant "c.location : Room" as sz

u->char ++: dropItem(i)

alt inventory contains Item
    char->t ++: setLocation(c.location)
    return
    char->sz ++: add(Item)
    return
end

char-->u --:

@enduml

@startuml pickup

title hallgatói tárgyfelvétel

actor "u : User" as u
participant "c : Character" as char
participant "i : Item" as t
participant "r : Room" as sz

u->char ++: pickup(i)

alt actions>0 && inventory.size()!=max
    char->sz ++: getItem(i)

    sz->t ++: setLocation(null)
    
    opt activeTransistorException
        t-->sz --: activeTransistorException
        sz-->char --: null
        char-->u --: false
    end

    t-->sz --:

    sz-->char --: i

    char->>char : addItem(i)

    char-->u --: true
else
    char-->u --: false
end


@enduml

@startuml okatoi_drop

Title oktatói tárgyeldobás

actor "u: Ai" as u
participant "c : Character" as char
participant "i : Item" as t
participant "c.location : Room" as sz

u->char ++: dropItem(i)

alt inventory contains Item
    char->t ++: setLocation(c.location)
    return
    char->sz ++: add(Item)
    return
end

char-->u --:

@enduml

'----------------------------------------'

@startuml oktatoi_pickup

title oktatói tárgyfelvétel

actor "u : AI" as u
participant "c : Character" as char
participant "i : Item" as t
participant "r : Room" as sz

u->char ++: pickup(i)

alt actions>0 && inventory.size()!=max
    char->sz ++: getItem(i)

    sz->t ++: setLocation(null)
    
    opt activeTransistorException
        t-->sz --: activeTransistorException
        sz-->char --: null
        char-->u --: false
    end

    t-->sz --:

    sz-->char --: i

    char->>char : addItem(i)

    char-->u --: true
else
    char-->u --: false
end


@enduml