@startuml drop

Title tárgyeldobás

participant Character as char
participant Item as t
participant Room as sz

opt tárgyeldobás [actions>0]
    alt inventory contains Item
        char->>t : setLocation(Room)
        char->>sz : add(Item)
        char->>char : decreaseActions()
    end
end

@enduml

@startuml pickup

title tárgyfelvétel

participant Character as char
participant Item as t
participant Room as sz

opt tárgyfelvétel [actions>0 && inventory.size()!=max]
    char->sz : askForItem
    'TODO: hogyan állapítjuk meg, hogy ez egy tranzisztor?'
    'ötlet: legyen egy pickup függvény'

    note over char #LightCoral: TODO: hogyan állapítjuk meg, hogy ez egy tranzisztor? \n ötlet: legyen egy pickup függvény

    alt a Tárgy egy aktivált tranzisztor
        sz-->char : null
    else
        sz-->char : Item
        char->>char : addItem(Item)
        char->>t : setLocation(null)
        char->>char : decreaseActions()
    end
end


@enduml