@startuml drop

Title tárgyeldobás

actor "u: User" as u
participant "c : Character" as char
participant "i : Item" as t
participant "r : Room" as sz

u->char ++: dropItem(i)

opt tárgyeldobás [actions>0]
    alt inventory contains Item
        char->>t : setLocation(Room)
        char->>sz : add(Item)
    end
end
char-->u --:

@enduml

@startuml pickup

title tárgyfelvétel

participant Character as char
participant Item as t
participant Room as sz

opt tárgyfelvétel [actions>0 && inventory.size()!=max]
    char->sz : getItems()
    return ArrayList<Item>

    char->>char : addItem(Item)
    char->t : setLocation(null)

    alt a Tárgy egy aktivált tranzisztor
        t-->char : false
    else
        t-->char : true
    end
end


@enduml