@startuml Round

title Egy játékkör

participant "g : GameEngine" as g
participant "s.location : Room" as sz
participant "destroom : Room" as dsz
participant "s : Student" as h
participant "p: Professor" as okt
participant "d : Door" as a
participant "lowDurabilityItem : Item" as t2
participant "usedItem : Item" as t

g->sz ++: checkGas()
group ref Gázosított Szoba
end
sz-->g --:

group ref Oktatói kör
    note over h: most az oktatók lépnek
end

g -> h ++: doRound()

group ref Move
note over h : A hallgató mozog
end



group ref tárgyfelvétel
end

group ref tárgyeldobás
end

opt tárgyhasználat [actions>0]
    h->t ++: activate()

    
        group activate Cups
        end

        group ref activate Rag
        end

        group ref activate Camembert
        end

        group ref activate Transistor
        end

    t-->h --:

end

loop for each item in inventory
    alt activated == true
        h->t2 ++: decreaseDurability()
        return

        alt lowDurabilityItem.durability == 0
            h->>t2 !!: delete
        end
    end
end

h-->g --:

group ref Szobamanipuláció
end
@enduml