@startuml Rucksack asks

participant Backpack as hát
!startsub GAS_RUCKSACK
!procedure $gasRuck($owner, $obj)
participant $obj
alt #LightSeaGreen gased = true
        g -> sz : checkGas()
        sz->$owner : protection(bool)
        $owner->hát : askIfGasProtection
        loop for each tárgy in hátizsák
            hát->$obj ++: areYouAntiGas(bool)
            return bool
        end
        alt van gázvédelme

            alt védelemnek van durabilitije
                hát->>$obj : decreaseDurability
                alt cooldown == 0
                    hát->>$obj !!: delete
                end
            end

            hát-->$owner : return true
            $owner-->sz : return true
        else
            hát-->$owner : return false
            $owner-->sz : return false
            sz->>$owner : paralyze
        end
        sz-->g
end
!endprocedure
!endsub

@enduml