@startuml Rucksack asks
participant Hátizsák as hát
participant Tárgy as t

'megcsinálni, hogy különböző lifeline-on legyenek a kitörölt tárgyak'

!startsub GAS_RUCKSACK
!procedure $gasRuck($owner)
alt #green gased = true
        sz->$owner ++: protection(bool)
        $owner->hát ++: askIfProtection
        loop for each tárgy in hátizsák
            hát->t ++: areYouDefensive(bool)
            return bool
        end
        alt van védelme
            hát->>hát : seeHiearchy

            alt védelemnek van cooldownja
                hát->>t : decreaseCooldown
                alt cooldown == 0
                    hát->>t !!: delete
                end
            end

            hát-->$owner --: return true
            $owner-->sz --: return true
        else
            sz->>$owner : paralyze
        end
end
!endprocedure
!endsub