@startuml gazed_room
Title Gázosított Szoba

participant "i : Item" as item
participant "c : Character" as char
participant "r : Room" as sz

alt #LightGreen gased = true
        sz->char ++: paralyze()
        loop for each tárgy in inventory
            char->item ++: protectMe("gas")

            return f: bool

            alt az item gázvédelmi

                alt védelemnek van durabilitije
                    char->item ++: decreaseDurability()
                    return
                
                    alt durability == 0
                        char->>item !!: delete
                    
                    end
                end

                note over item : break loop
            else
                char->>char : setParalyzed()
            end

        end
        char-->sz --:
end

@enduml