@startuml gazed_room
Title Gázosított Szoba

participant Item as item
participant Character as char
participant Room as sz

alt #LightGreen gased = true
        sz->>char : paralyze()
        loop for each tárgy in inventory
            char->item: protectMe("gas")

            alt az item gázvédelmi

                alt védelemnek van durabilitije
                    char->>item : decreaseDurability()
                
                    alt durability == 0
                        item->>item !!: delete
                    
                    end
                end

                item-->char : return true
                note over item : break loop
            else
                item-->char : return false
                char->>char : setParalyzed()
            end

        end
end

@enduml