@startuml Rucksack asks
participant Hátizsák as hát

!startsub GAS_RUCKSACK
!procedure $gasRuck($owner, $obj)
participant $obj
alt #LightSeaGreen gased = true
        sz->$owner ++: protection(bool)
        $owner->hát ++: askIfProtection
        loop for each tárgy in hátizsák
            hát->$obj ++: areYouDefensive(bool)
            return bool
        end
        alt van védelme
            hát->>hát : seeHiearchy

            alt védelemnek van cooldownja
                hát->>$obj : decreaseCooldown
                alt cooldown == 0
                    hát->>$obj !!: delete
                end
            end

            hát-->$owner --: return true
            $owner-->sz --: return true
        else
            sz->>$owner : paralyze
        end
end
!endprocedure
!endsub

@enduml