@startuml Round

title Hallgatói kör

participant GameEngine as g
participant Room as sz
participant Student as h
participant Professor as okt
participant Door as a
participant Backpack as hát
participant "Item1" as t
participant "Item2" as t2

!includesub gased_rucksack.puml!GAS_RUCKSACK

g -> hát : decreaseDurability()
loop for each active_object in hátizsák
    hát->>t2 : decreaseDurability()

    alt cooldown == 0
        t2->>t2 !!: delete
    end
end
hát-->g

$gasRuck("h", "Item3")

group ref Round okt 
    note over h: most az oktatók lépnek
end

g -> h : doRound()
opt #lightyellow Move [if skipturn==false]
    h->sz : Move

    loop door_num
        sz->a ++: askDirections
        return ret(directions)
    end

    alt Szoba.capacity!=full && there is entrance
        sz-->h : MoveAccept
        sz->>sz : setParticipants
        h->>h : setRoom    
    else
        sz-->h : MoveDeny
    end

    $gasRuck("h", "Item4")
end

newpage

loop max 3
    opt tárgyfelvétel
        h->sz : askForItem
        alt a Tárgy egy aktivált tranzisztor
            sz-->h : deny
        end
        sz-->h : ret(Item)
        h->>hát : add(Item)
    end

    opt tárgyeldobás
        h->hát ++: askForItem
        hát-->h --: ret(Item)
        h->>sz : add(Item)
    end

    opt tárgyhasználat
        group perform effect

            hát->>t : effect
            alt védelmet aktivál
                    t->>t : setValid
            end
            alt ha a tárgy magán kívül mást is módosít
                t->hát ++ : getSzoba
                hát->h ++: getSzoba
                return szoba
                hát-->t --: szoba
                t->>sz : invokeEffect()

                note right of t : az invokeEffect azt jelenti, hogy a védelmi tárgy hatásának\n megfelelő függvényt hívja meg

                alt gázosítás
                    sz->>sz : setGased
                end

                alt oktatót bénít
                    sz-->okt : paralyze
                end

                alt tranzisztor
                    group ref tranzisztorhasználat
                    end
                end
            end
        end
    end
end
h-->g

group ref Building changing
end
@enduml