@startuml Round_okt

title Oktatói kör

participant "g : GameEngine" as g

participant "r : Room" as sz

participant "s : Student" as h
participant "p : Professor" as okt
participant "i : Item" as t

g->okt ++: doRound()

group ref Oktatói Move
note over okt : Az oktató lép
end

okt->sz ++: killStudents()
alt #LightPink van hallgató a szobában
    loop for each hallgató in szoba

        sz -> h ++: die()

        loop for each Item in inventory
            note over t : ha az adott védelmi tárgy a hiearchiában a következő
            h->t ++: protectMe("professor")

            group ref Rag
            end

            t-->h --: bool

            h->t ++: decreaseDurability()
            return bool

            alt bool = false
                h->>t !!: delete
            end         
        end

        alt egyik tárgy sem tért vissza igazzal
            h-->sz --: true
            sz ->> h !!: delete 
        else
            h-->sz --: false
        end
    end
end

sz --> okt --:

group ref oktatói tárgyfelvétel
end

group ref oktatói tárgyeldobás
end

okt --> g
@enduml