@startuml Round_okt

title Oktatói kör

participant GameEngine as g

participant Room as sz

participant Student as h
participant Professor as okt
participant Item as t

g->okt : doRound()

group ref Move
note over okt : Az oktató lép
end

okt->sz : killStudents()
alt #LightPink van hallgató a szobában
    loop for each hallgató in szoba

        sz -> h : die()

        loop for each Item in inventory
            note over t : ha az adott védelmi tárgy a hiearchiában a következő
            h->t : protectMe("professor")

            alt a tárgy védelmi

                alt Rag
                    group ref Rag
                    end
                end

                t-->h : true

                alt védelemnek van durabilije
                t->t : decreaseDurability()
                    alt durability == 0
                        t->>t !!: delete
                    end
                end
                note over t : break loop

                h-->sz
            else
                t-->h : false
            end           
        end

        alt egyik tárgy sem tért vissza igazzal
            h-->sz
            h ->> h !!: delete 
        end
    end
end

sz --> okt

group ref tárgyfelvétel
end

group ref tárgyeldobás
end

okt --> g
@enduml