@startuml Round_okt

title Oktatói kör

participant Room as sz
participant Student as h
participant Professor as okt
participant Door as a
participant Item1 as t
participant Backpack as hát
participant GameEngine as g

!includesub gased_rucksack.puml!GAS_RUCKSACK

$gasRuck("okt", "Item2")

opt #LightYellow Move
    okt->szoba : Move(Professor)

    'TODO'
    loop door_num
        sz->a ++: askDirections
        return ret(directions) /
    end

    alt Szoba.capacity!=full && there is entrance
        sz-->okt : true
        sz->>sz : setParticipants
        okt->>okt : setRoom(Szoba)  
    else
        sz-->okt : false
    end

    $gasRuck("okt", "Item3")
end

' ---------------------- '
newpage

okt->sz : thereIsStudent()
alt #LightPink van hallgató a szobában
    loop for each hallgató in szoba

        okt -> h : askIfDefense(bool)

        h->hát : checkDefense
        loop for each tárgy in hátizsák
            hát->t ++: isDefensive
            return isDefensive
        end
        
        alt van védelmi tárgy
            hát->>hát : choose_highest_in_hiearchy()

            note right of hát : kiválasztja egy sorrendnek megfelelően,\n melyik tárgyat használja el
            alt #LightSeaGreen a védelmi tárgynak van hatása

                group perform effect

                    hát->>t : effect
                    t->hát ++ : getRoom
                    hát->okt ++: getRoom
                    return szoba
                    hát-->t --: szoba
                    t->>sz : invokeEffect()

                    note right of t : az invokeEffect azt jelenti, hogy a védelmi tárgy hatásának\n megfelelő függvényt hívja meg
                end
            else
                alt védelemnek van durabilije
                hát->>t : decreaseDurability
                alt cooldown == 0
                    hát->>t !!: delete
                end
            end
            end

            hát-->h : return (true)
            h-->okt : return (true)
        else
            hát-->h : return (false)
            h-->okt : return (false)
            okt ->> h !! : kibuktat            
        end
    end
    else
        sz --> okt : false
end

loop max 3
    opt tárgyfelvétel
        okt->sz : askForItem
        alt a Tárgy egy aktivált tranzisztor
            sz-->okt : deny
        end
        sz-->okt : ret(Item)
        okt->>hát : add(Item)
    end

    opt tárgyeldobás
        okt->hát ++: askForItem
        hát-->okt --: ret(Item)
        okt->>sz : add(Item)
    end
end
@enduml