@startuml teleport

Title A tranzisztor használat (teleportálás) akció

Participant "Tranzistor A" as tranz
participant "Tranzistor B" as tranz2
Participant Student as h

alt A kérés valid (van a célszobában párosított tranzisztora)

    tranz->h : ok
    h->>] : move

    group ref move
        note over h : az ajtóellenőrzést kivéve a mozgás a megszokott módon történik.
    end

    tranz->tranz2 : unpair
else
    tranz-->h : deny
end

@enduml

'------------------------------------------------'

@startuml pair

title A tranzisztor párosítás akció

Participant "Tranzistor A" as tranz1
participant "Tranzistor B" as tranz2
participant Backpack as hát
participant Student as h

group ref tárgyhasználat
    note over h : a hallgató tranzisztort aktivál
end

tranz1->>tranz1 : setRoom(null)
note right : beállítja, hogy nincs szobában

tranz1->hát ++: getTranzistors
return TranzisztorList


alt nincs másik nem aktív tranzisztor
    tranz1->>hát : sendDeny
    hát->>h : Deny
else
    tranz1->h ++: chooseTranzisztor(TranzisztorList)
    return tranzisztor

    tranz1->>tranz2 : pair
end

@enduml

'---------------------------------------------'

@startuml place

title A tranzisztor elhelyezése

Participant "Tranzistor A" as tranz1
Participant "Tranzistor B" as tranz2
participant Backpack as hát
participant Student as h

group ref tárgyletétel
note over h : a hallgató tranzisztort dob el
end

hát->>tranz1 : notifyOnDrop

tranz1->hát ++: getRoom
return szoba

tranz1->tranz2 ++: isPlaced()
return bool

alt bool == true
tranz1->>tranz2 : unpair()
end

tranz1->>tranz1 : setLocation(szoba)
note right: beállítja, hogy milyen szobába került

@enduml