@startuml teleport
Participant "Tranzisztor A" as tranz
participant "Tranzisztor B" as tranz2
participant "Hátizsák" as hát
Participant Hallgató as h

note over tranz2 : a célszobában levő tranzisztor (ha van)

h->tranz : usageReq(goal)
tranz->map : is there a transistor?
return bool

tranz->>tranz : isValid(goal)

alt A kérés valid (van a célszobában párosított tranzisztora)

    tranz-->h : ok
    h->>] : move

    group ref move
    end

    tranz->tranz : unpair
    return ok
else
    tranz-->h : deny
end

@enduml

'------------------------------------------------'

@startuml pair
Participant "Tranzisztor A" as tranz1
participant "Tranzisztor B" as tranz2
participant Hátizsák as hát
participant Hallgató as h

group ref tárgyhasználat
    note over h : a hallgató tranzisztort aktivál
end

tranz1->>tranz1 : setSzoba(null)
note right : beállítja, hogy nincs szobában

tranz1->hát ++: getTranzistors
return TranzisztorList


alt nincs másik nem aktív tranzisztor
    tranz1->>hát : sendDeny
    hát->>h : Deny
else
    tranz1->h ++: chooseTranzisztor(TranzisztorList)
    return tranzisztor

    tran1->>tranz2 : pair
end

@enduml

'---------------------------------------------'

@startuml place

Participant "Tranzisztor A" as tranz1
Participant "Tranzisztor B" as tranz2
participant Hátizsák as hát
participant Hallgató as h

group ref tárgyletétel
note over h : a hallgató tranzisztort dob el
end

hát->>tranz1 : notifyOnDrop

tranz1->hát ++: getSzoba
return szoba

tranz1->tranz2 ++: isPlaced()
return bool

alt bool == true
tranz1->>tranz2 : unpair()
end

tranz1->>tranz1 : setPlace(szoba)
note right: beállítja, hogy milyen szobába került

@enduml