@startuml tanár támad sikeresen

title 11

actor Skeleton as sk
participant "r1 : Room" as r
participant "c1 : Character" as s
participant "f1 : FFP2" as c

sk->r ++: killStudents()

r -> s ++: die()

s->c ++: protectMe("professor")
c-->s --: false

s-->r --: true

r->>s !!: delete

r-->sk --:

@enduml