@startuml rag aktiválása

title 18

actor Skeleton as sk
participant "s1 : Student" as s
participant "rg1 : Rag" as rg
participant "r1 : Room" as r

sk->s ++: useItem(rg1)
s->rg ++: activate()

rg->>rg : activated = true

rg->s ++: dropItem(rg1)

s -> r ++: addItem(rg)
r-->s --:

s->rg ++: setLocation(r)
rg-->s --:

s-->rg --:

rg-->s --:

s-->sk --:

@enduml