@startuml Rag decreaseDurability + paralyzeProfessors

title 18

actor Skeleton as sk
participant "g1 : gameEngine" as g
participant "r1 : Room" as room
participant "rg1 : Rag" as r
participant "p1 : Professor" as p

sk->g ++: playOnePhase()
g->r ++: decreaseDurability()

r->room ++: paralyzeProfessors()
return

r-->g --: true
g-->sk --:

@enduml