@startuml Rag decreaseDurability + megsemmisülés

title 20

actor Skeleton as sk
participant "g1 : gameEngine" as g
participant "r1 : Room" as room
participant "rg1 : Rag" as r
participant "p1 : Professor" as p

sk->g ++: playOnePhase()
g->r ++: decreaseDurability()

r-->g --: false

g->>r !!: delete

g-->sk --:

@enduml