@startuml camembert

title 21

actor Skeleton as sk
participant "s1 : Student" as s
participant "c1 : Camembert" as c
participant "r1 : Room" as r

sk->s ++: useItem(c)

s -> c ++: activate()

c -> s ++: getLocation()
s--> c --: r1

c->r ++: setGassed()

r-->c --:

c-->s --:

s->c ++: decreaseDurability()
return false

s->>c !!: delete

sk<--s --:


@enduml