@startuml sliderule

title 23

actor Skeleton as sk
participant "sl1 : SlideRule" as sl
participant "s1 : Student" as s
participant "r1 : Room" as r
participant "g1 : GameEngine" as g

sk->s ++: addItem(sl)
s->r ++: removeItem(sl)

r->sl ++: setLocation(null)
sl-->r --:

r-->s --: sl

s->g ++: endgame()

g-->s --:

s-->sk --:

@enduml

