@startuml transistor drop 1

title 24

actor Skeleton as sk
participant "s1 : Student" as s
participant "r1 : Room" as r
Participant "t1 : Tranzistor" as tranz1
participant "t2 : Transistor" as tranz2

sk->s ++: dropItem(t1)

s-> tranz1 ++: setLocation(r1)

tranz1->tranz2 ++: getLocation()
tranz2-->tranz1 --: null

tranz1 ->> tranz1 : location = r1

s <-- tranz1 --:

s -> r ++: add(t1)
r-->s --:

s-->sk --:

@enduml