@startuml transistor can't use

title 26

actor Skeleton as sk
participant "s1 : Student" as s
participant "t1 : Transistor" as t1
participant "t2 : Transistor" as t2

sk -> s ++: useItem(t1)

s->t1 ++: activate()

t1 -> t2 ++: getLocation()
t2 --> t1 --: null

t1 --> s --:

s-->sk --:

@enduml