@startuml transistor + gázos + védekezik

title 30

actor Skeleton as sk
participant "s1 : Student" as s
participant "t1 : Transistor" as t1
participant "t2 : Transistor" as t2
participant "f1 : FFP2" as f
participant "r1 : Room" as r
participant "s1.location : Room" as r2

sk -> s ++: useItem(t1)

s->t1 ++: activate()

t1 -> t2 ++: getLocation()
t2 --> t1 --: r1

t1 -> s ++: getLocation()
s --> t1 --: s1.location

t1 -> r ++: addCharacter(s1)

r->s ++: setLocation(r1)
s-->r --:

r->s ++: setParalyzed()

s->f ++: protectMe("gas")

f-->s --: true

s-->r --:

r-->t1 --: true

t1 -> r2 ++: removeCharacter(s1)
r2 --> t1 --:

t1-->s --:

s-->sk --:

@enduml