@startuml kilépés

actor Skeleton as sk

participant "g1 : GameEngine" as g
participant "s: Student" as s
participant "p: Professor" as p
participant "r: Room" as r
participant "f: FFP2" as f

sk->g ++: endGame()

g -> s !!: delete
g -> p !!: delete
g -> r !!: delete
g -> f !!: delete

g-->sk --:
@enduml