@startuml ffp2 + nem jár le az idő

Title 5

actor Skeleton as sk
participant "d1 : Door" as d
participant "c1 : Character" as c
participant "f1 : FFP2" as f
participant "r1 : Room" as r1
participant "r2 : Room" as r2

sk -> c ++: move(d1)

c->d ++: accept(c1, r1)
d-->c --: true

c -> d ++: getNeighbour(r1)

d-->c --: r2

c->r2 ++: addCharacter(c1)

r2->c ++: setParalyzed()

c->f ++: protectFromGas()

f-->c --: true

c->f ++: decreaseDurability()
return true

c-->r2 --:

r2 -->c --:

c->r1 ++: removeCharacter(c1)
return

c-->sk --:

@enduml