@startuml Gázos szoba

Title 5

actor Skeleton as sk
participant "d1 : Door" as d
participant "c1 : Character" as c
participant "f : FFP2" as f
participant "r1 : Room" as r1
participant "r3 : Room" as r3

sk -> c ++: move(d1)

c->d ++: accept(c1, r1)
d-->c --: true

c -> d ++: getNeighbour(r1)

d-->c --: r3

c->r3 ++: addCharacter(c)

r3->c ++: setParalyzed()

c->f ++: protectMe("gas")

f-->c --: true

c-->r3 --: false

r3 -->c --:

c->r1 ++: removeCharacter(c)
return

c-->sk --:

@enduml