@startuml Targyfelvétel sikeres

Title 6

actor Skeleton as s
participant "c1 : Character" as c
participant "r1 : Room" as r4
participant "f1 : FFP2" as i

s->c ++: addItem(f1)

c -> r4 ++: removeItem(f1)

r4 -> i ++: setLocation(null)
i-->r4 --:

r4 --> c --: f1

c->i ++: setOwner(c1)
return

c-->s --:

@enduml