@startuml Targyfelvéte sikertelen

Title 7

actor Skeleton as s
participant "c1 : Character" as c
participant "f1 : FFP2" as f
participant "f1.location : Room" as r

s->c ++: addItem(f1)

c-->s --:

@enduml