@startuml Tárgyeldobás

Title 8

actor "Skeleton" as u
participant "c1 : Character" as char
participant "f1 : FFP2" as t
participant "r1 : Room" as sz

u->char ++: dropItem(f1)

char->t ++: setLocation(r1)
return

char->sz ++: addItem(f1)
return

char-->u --:

@enduml