@startuml ffp2 + lejár az idő
Title 9

participant "f1 : FFP2" as f
participant "c1 : Character" as char
participant "r1 : Room" as sz

sz->char ++: setParalyzed()

char->f ++: protectFromGas()
return true

char->f ++: decreaseDurability()

return false

char->>f !!: delete

char-->sz --: