@startuml Move
participant Szoba as sz
participant Karakter as k

k->sz : Move
alt Szoba.capacity!=full && there is a door
    sz-->k : MoveAccept
    sz->sz : setParticipants
    k->k : setRoom
else
    sz-->k : MoveDeny
end

@enduml